### ISSUE TITLE
经测试，无效

### ISSUE THREAD

**Issue by ellicefix** [ache051/mac_cantonese#1]
系统：Sierra 
版本：10.12.2
无法挂载到系统输入源
复现率100%

**Comment by ache051** [comment]
I suspect that it could be a privilege problem for putting downloaded files into system folders 
Try this:
1) Open a blank document with TextEdit
2) Go to Format > Make Plain Text
3) Open the downloaded mac_cantonese.inputplugin file with another instance of TextEdit
4) Copy everything over from mac_cantonese.inputplugin to the blank document
5) Save the new document with the name mac_canton.inputplugin
6) Close all TextEdit instances
7) Double-click on mac_canton.inputplugin
8) Check if the input method appears

**Comment by ellicefix** [comment]
Did you have a try?

**Comment by ellicefix** [comment]
成功了，谢谢！

**Comment by ache051** [comment]
Thanks for reporting back! I will close the issue now.
